"""add_rbac_tables

Revision ID: 56baaf72e1b8
Revises: 9913ba09c4e2
Create Date: 2026-07-21 14:42:33.867375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56baaf72e1b8'
down_revision: Union[str, Sequence[str], None] = '9913ba09c4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='权限主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限标识，如 article:delete'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='权限说明'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称：admin / editor / user'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.alter_column('article', 'id',
               existing_type=mysql.INTEGER(),
               comment='文章主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='文章标题',
               existing_nullable=False)
    op.alter_column('article', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='URL别名，SEO友好',
               existing_nullable=False)
    op.alter_column('article', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='文章正文',
               existing_nullable=False)
    op.alter_column('article', 'summary',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='文章摘要',
               existing_nullable=True)
    op.alter_column('article', 'cover_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='封面图URL',
               existing_nullable=True)
    op.alter_column('article', 'status',
               existing_type=mysql.ENUM('draft', 'published', collation='utf8mb4_unicode_ci'),
               comment='文章状态：draft草稿、published已发布',
               existing_nullable=False)
    op.alter_column('article', 'view_count',
               existing_type=mysql.INTEGER(),
               comment='阅读量计数器',
               existing_nullable=False)
    op.alter_column('article', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='软删除标记',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('article', 'author_id',
               existing_type=mysql.INTEGER(),
               comment='作者用户ID',
               existing_nullable=False)
    op.alter_column('article', 'category_id',
               existing_type=mysql.INTEGER(),
               comment='所属分类ID',
               existing_nullable=True)
    op.alter_column('article', 'published_at',
               existing_type=mysql.DATETIME(),
               comment='发布时间',
               existing_nullable=True)
    op.alter_column('article', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('article', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('article_tag', 'article_id',
               existing_type=mysql.INTEGER(),
               comment='文章ID',
               existing_nullable=False)
    op.alter_column('article_tag', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment='标签ID',
               existing_nullable=False)
    op.alter_column('category', 'id',
               existing_type=mysql.INTEGER(),
               comment='分类主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类名称',
               existing_nullable=False)
    op.alter_column('category', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='分类描述',
               existing_nullable=True)
    op.alter_column('category', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.add_column('comment', sa.Column('depth', sa.Integer(), nullable=False, comment='评论层级：0=顶级，1=一级回复，2=二级回复'))
    op.alter_column('comment', 'id',
               existing_type=mysql.INTEGER(),
               comment='评论主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('comment', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='评论内容',
               existing_nullable=False)
    op.alter_column('comment', 'article_id',
               existing_type=mysql.INTEGER(),
               comment='所属文章ID',
               existing_nullable=False)
    op.alter_column('comment', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='评论用户ID',
               existing_nullable=False)
    op.alter_column('comment', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment='父评论ID，NULL表示顶级评论',
               existing_nullable=True)
    op.alter_column('comment', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='软删除标记',
               existing_nullable=False)
    op.alter_column('comment', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='评论时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.create_index('ix_comment_article_parent', 'comment', ['article_id', 'parent_id'], unique=False)
    op.alter_column('favorite', 'id',
               existing_type=mysql.INTEGER(),
               comment='收藏主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('favorite', 'article_id',
               existing_type=mysql.INTEGER(),
               comment='被收藏文章ID',
               existing_nullable=False)
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='收藏用户ID',
               existing_nullable=False)
    op.alter_column('favorite', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='收藏时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('like', 'id',
               existing_type=mysql.INTEGER(),
               comment='点赞主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('like', 'article_id',
               existing_type=mysql.INTEGER(),
               comment='被点赞文章ID',
               existing_nullable=False)
    op.alter_column('like', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='点赞用户ID',
               existing_nullable=False)
    op.alter_column('like', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='点赞时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('tag', 'id',
               existing_type=mysql.INTEGER(),
               comment='标签主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='标签名称',
               existing_nullable=False)
    op.alter_column('tag', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               comment='用户主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='登录用户名',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='bcrypt密码哈希值',
               existing_nullable=False)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('user', 'admin', collation='utf8mb4_unicode_ci'),
               comment='角色(向后兼容，新代码优先用 roles 关系)',
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='账号是否激活',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='注册时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='注册时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='账号是否激活',
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('user', 'admin', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='角色(向后兼容，新代码优先用 roles 关系)',
               existing_nullable=False)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='bcrypt密码哈希值',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='登录用户名',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tag', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='标签名称',
               existing_nullable=False)
    op.alter_column('tag', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='标签主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('like', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='点赞时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('like', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='点赞用户ID',
               existing_nullable=False)
    op.alter_column('like', 'article_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='被点赞文章ID',
               existing_nullable=False)
    op.alter_column('like', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='点赞主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('favorite', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='收藏时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('favorite', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='收藏用户ID',
               existing_nullable=False)
    op.alter_column('favorite', 'article_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='被收藏文章ID',
               existing_nullable=False)
    op.alter_column('favorite', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='收藏主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_comment_article_parent', table_name='comment')
    op.alter_column('comment', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='评论时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('comment', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('comment', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父评论ID，NULL表示顶级评论',
               existing_nullable=True)
    op.alter_column('comment', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='评论用户ID',
               existing_nullable=False)
    op.alter_column('comment', 'article_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属文章ID',
               existing_nullable=False)
    op.alter_column('comment', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='评论内容',
               existing_nullable=False)
    op.alter_column('comment', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='评论主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('comment', 'depth')
    op.alter_column('category', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('category', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='分类描述',
               existing_nullable=True)
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=False)
    op.alter_column('category', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分类主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('article_tag', 'tag_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False)
    op.alter_column('article_tag', 'article_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文章ID',
               existing_nullable=False)
    op.alter_column('article', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('article', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('article', 'published_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='发布时间',
               existing_nullable=True)
    op.alter_column('article', 'category_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属分类ID',
               existing_nullable=True)
    op.alter_column('article', 'author_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='作者用户ID',
               existing_nullable=False)
    op.alter_column('article', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('article', 'view_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='阅读量计数器',
               existing_nullable=False)
    op.alter_column('article', 'status',
               existing_type=mysql.ENUM('draft', 'published', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='文章状态：draft草稿、published已发布',
               existing_nullable=False)
    op.alter_column('article', 'cover_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='封面图URL',
               existing_nullable=True)
    op.alter_column('article', 'summary',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='文章摘要',
               existing_nullable=True)
    op.alter_column('article', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='文章正文',
               existing_nullable=False)
    op.alter_column('article', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='URL别名，SEO友好',
               existing_nullable=False)
    op.alter_column('article', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='文章标题',
               existing_nullable=False)
    op.alter_column('article', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='文章主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('user_role')
    op.drop_table('role_permission')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
