"""add is_deleted to article

Revision ID: 9913ba09c4e2
Revises: 06ff967ccf02
Create Date: 2026-06-25 16:25:48.270414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9913ba09c4e2'
down_revision: Union[str, Sequence[str], None] = '06ff967ccf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    # 增删列会隐式删 FULLTEXT 索引，必须重建
    op.drop_index(op.f('ft_title_content'), table_name='article', mysql_prefix='FULLTEXT')
    op.create_index(op.f('ft_title_content'), 'article', ['title', 'content'],
                    unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ft_title_content'), 'article', ['title', 'content'], unique=False, mysql_prefix='FULLTEXT')
    op.drop_column('article', 'is_deleted')
    # ### end Alembic commands ###
