"""add_notification_table

Revision ID: 9e816a8affe8
Revises: 56baaf72e1b8
Create Date: 2026-07-21 15:06:39.192681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e816a8affe8'
down_revision: Union[str, Sequence[str], None] = '56baaf72e1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='通知主键ID'),
    sa.Column('recipient_id', sa.Integer(), nullable=False, comment='接收通知的用户ID'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='触发通知的用户ID'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='通知类型：like/comment/reply/favorite'),
    sa.Column('message', sa.Text(), nullable=False, comment='通知内容'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='关联文章ID'),
    sa.Column('comment_id', sa.Integer(), nullable=True, comment='关联评论ID（回复通知用）'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='通知时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
